version: "3.2"
services:
  web:
    image: app
    command: bash -c "flask db upgrade && python app.py"
    ports:
     - "5000:5000"
    depends_on:
     - celery
    links:
     - redis
    environment:
     - DB_USER=${DB_USER}
     - DB_PASSWORD=${DB_PASSWORD}
     - DB_NAME=${DB_NAME}
     - DB_HOST=postgres_db
     - DB_PORT=5432
     - CELERY_BROKER_URL=redis://redis:6379/0
  celery:
     build: .
     image: app
     command: "celery -A app.celery worker --loglevel=info"
     user: nobody
     depends_on:
     - postgres_db
     links:
     - redis
     environment:
     - DB_USER=${DB_USER}
     - DB_PASSWORD=${DB_PASSWORD}
     - DB_NAME=${DB_NAME}
     - DB_HOST=postgres_db
     - DB_PORT=5432
     - CELERY_BROKER_URL=redis://redis:6379/0
  postgres_db:
    restart: "always"
    image: postgres:11
    ports:
      - "5432:5432"
    labels:
      description: "Postgresql Database"
      service: "postgresql"
    environment:
      - DEBUG=false
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME:?DB_NAME not specified}
  redis:
    image: redis
    ports:
    - '6379:6379'
